// Turns ../index.html (the game) into game.js: the same script, run headless in Node with
// enough of a fake DOM that the simulation boots and exposes window.__SRV.
'use strict';
const fs = require('fs'), path = require('path');
const SRC = path.join(__dirname, '..', 'index.html');
const OUT = path.join(__dirname, 'game.js');

function build(){
  const html = fs.readFileSync(SRC, 'utf8');
  const a = html.indexOf('<script>') + 8, b = html.lastIndexOf('</script>');
  const script = html.slice(a, b);
  const out = `// generated by build.js from ../index.html — do not edit
'use strict';
module.exports = function boot(){
  // a canvas context / element that swallows everything
  const sink = new Proxy(function(){}, { get:(t,k)=> k==='then' ? undefined : (k==='length'?0:sink), set:()=>true, apply:()=>sink, construct:()=>sink });
  const el = () => ({ style:{}, dataset:{}, textContent:'', innerHTML:'', value:'', className:'', width:0, height:0, disabled:false, children:[], firstChild:null,
    classList:{ add(){}, remove(){}, toggle(){} }, addEventListener(){}, appendChild(){}, removeChild(){}, remove(){}, select(){}, closest(){ return null; },
    querySelector(){ return el(); }, querySelectorAll(){ return []; }, getContext(){ return sink; }, focus(){} });
  const document = { getElementById: el, createElement: el, querySelector: el, querySelectorAll: () => [], body: el(), hidden:false };
  const window = { __IS_SERVER:true, innerWidth:1280, innerHeight:720, devicePixelRatio:1, addEventListener(){}, location:{ search:'', protocol:'srv:' },
    localStorage:{ getItem(){ return null; }, setItem(){} } };
  const navigator = { maxTouchPoints:0, clipboard:{ writeText: async()=>{} } };
  const localStorage = window.localStorage, location = window.location;
  const addEventListener = () => {}, requestAnimationFrame = () => 0, cancelAnimationFrame = () => {};
  const fetch = () => Promise.reject(new Error('no network in the sim'));
  const MutationObserver = undefined, RTCPeerConnection = undefined, WebSocket = undefined, AudioContext = undefined, webkitAudioContext = undefined;
  const setInterval = () => 0;   // the page's lobby poller has nothing to poll here
  const alert = () => {};
${script}
  return window.__SRV;
};
`;
  fs.writeFileSync(OUT, out);
  return OUT;
}
module.exports = build;
if(require.main === module) console.log('built', build());
